import sys
from types import SimpleNamespace

import pytest

from miles.utils.tracking_utils import trackio_utils


def _args(**overrides):
    values = {
        "env_report": None,
        "rank": 0,
        "use_trackio": True,
        "wandb_project": "wproj",
        "wandb_group": "wgroup",
        "trackio_project": None,
        "trackio_run_name": None,
        "trackio_group": None,
        "trackio_space_id": None,
        "trackio_server_url": None,
        "trackio_dir": None,
    }
    values.update(overrides)
    return SimpleNamespace(**values)


class _FakeTrackio:
    def __init__(self):
        self.init_calls = []
        self.log_calls = []
        self.finish_calls = 0

    def init(self, **kwargs):
        self.init_calls.append(kwargs)
        # trackio.init returns a Run; expose .name so the primary can capture the
        # resolved (possibly auto-generated) run name.
        return SimpleNamespace(name=kwargs.get("name") or "auto-generated-name")

    def log(self, metrics, step=None):
        self.log_calls.append((metrics, step))

    def finish(self):
        self.finish_calls += 1


@pytest.fixture
def fake_trackio(monkeypatch):
    fake = _FakeTrackio()
    # Functions import trackio lazily, so injecting into sys.modules is enough.
    monkeypatch.setitem(sys.modules, "trackio", fake)
    # Reset the once-only local-secondary warning flag for isolation.
    monkeypatch.setattr(trackio_utils, "_warned_local_secondary", False)
    # Avoid leaking TRACKIO_DIR between tests.
    monkeypatch.delenv("TRACKIO_DIR", raising=False)
    monkeypatch.delenv("TRACKIO_SERVER_URL", raising=False)
    monkeypatch.delenv("TRACKIO_SPACE_ID", raising=False)
    return fake


def test_primary_init_starts_run_and_propagates_name(fake_trackio):
    args = _args()
    active = trackio_utils.init_trackio(args, primary=True)

    assert active is True
    assert len(fake_trackio.init_calls) == 1
    call = fake_trackio.init_calls[0]
    # Falls back to wandb naming.
    assert call["project"] == "wproj"
    assert call["name"] == "wgroup"
    assert call["group"] == "wgroup"
    assert call["resume"] == "allow"
    assert isinstance(call["config"], dict)
    # Resolved name propagated for secondary ranks.
    assert args.trackio_run_name == "wgroup"


def test_primary_captures_autogenerated_name_when_unset(fake_trackio):
    # Neither trackio-run-name nor wandb-group set -> name resolves to None and
    # trackio auto-generates one; the primary must propagate that resolved name
    # so secondary ranks attach to the same run.
    args = _args(wandb_group=None, trackio_run_name=None)
    trackio_utils.init_trackio(args, primary=True)

    assert fake_trackio.init_calls[0]["name"] is None
    assert args.trackio_run_name == "auto-generated-name"


def test_trackio_overrides_take_precedence(fake_trackio):
    args = _args(trackio_project="tproj", trackio_run_name="trun", trackio_group="tgrp")
    trackio_utils.init_trackio(args, primary=True)

    call = fake_trackio.init_calls[0]
    assert call["project"] == "tproj"
    assert call["name"] == "trun"
    assert call["group"] == "tgrp"


def test_secondary_remote_attaches_to_same_run(fake_trackio):
    args = _args(trackio_server_url="http://host:7860", trackio_run_name="wgroup")
    active = trackio_utils.init_trackio(args, primary=False)

    assert active is True
    call = fake_trackio.init_calls[0]
    assert call["name"] == "wgroup"
    assert call["server_url"] == "http://host:7860"
    assert call["resume"] == "allow"


def test_secondary_local_is_noop_and_warns_once(fake_trackio, caplog):
    args = _args()
    with caplog.at_level("WARNING"):
        active1 = trackio_utils.init_trackio(args, primary=False)
        active2 = trackio_utils.init_trackio(args, primary=False)

    assert active1 is False and active2 is False
    # Never initialised a run on a local secondary.
    assert fake_trackio.init_calls == []
    # Warning emitted exactly once.
    warnings = [r for r in caplog.records if "local mode" in r.getMessage()]
    assert len(warnings) == 1


def test_disabled_returns_false_and_clears_run_name(fake_trackio):
    args = _args(use_trackio=False, trackio_run_name="stale")
    active = trackio_utils.init_trackio(args, primary=True)

    assert active is False
    assert args.trackio_run_name is None
    assert fake_trackio.init_calls == []


def test_trackio_dir_sets_env(fake_trackio, monkeypatch, tmp_path):
    target = tmp_path / "trackio_store"
    args = _args(trackio_dir=str(target))
    trackio_utils.init_trackio(args, primary=True)

    import os

    assert os.environ.get("TRACKIO_DIR") == str(target)
    assert target.exists()


def test_log_and_finish_delegate(fake_trackio):
    trackio_utils.log_metrics({"train/loss": 0.5, "train/step": 3}, step=3)
    trackio_utils.finish()

    assert fake_trackio.log_calls == [({"train/loss": 0.5, "train/step": 3}, None)]
    assert fake_trackio.finish_calls == 1


def test_backend_inactive_skips_log_and_finish(fake_trackio):
    from miles.utils.tracking_utils.base import TrackioBackend

    backend = TrackioBackend()
    args = _args(use_trackio=False)
    backend.init(args, primary=True)

    backend.log({"a": 1}, step=1)
    backend.finish()

    assert fake_trackio.log_calls == []
    assert fake_trackio.finish_calls == 0
